# Site settings
title: "Minsu Kim"


# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Minsu Kim"
resume_title:                   "M.S. Candidate of Teralab KAIST"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "min-su@kaist.ac.kr"




display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, this is Minsu Kim. I'm pursuing an M.S. degree in the School of Electrical Engineering at KAIST, advised by Prof. Joungho Kim. My current research interest includes AI/ML/DL application to electrical design automation (EDA) for signal integrity (SI). I'm currently working on building Deep Reinforcement Learning (DRL) frameworks for solving NP-hard routing problems that can apply to PCB/Interposer routing. My target HW of routing is the GPU-Memory interconnection of the GDDR6 (PCB) module and HBM (Interposer) module.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_skills:    true
resume_section_education:       true
resume_section_experience:      true
resume_section_projects:        true
resume_section_recognition:        true

# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/as12088"
  resume_linkedin_url:          "https://www.linkedin.com/in/minsu-kim-5693061a5/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
